"""Launch readiness packet generator."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any

import yaml
from rich.console import Console

from pluto_aguard import __version__
from pluto_aguard.models import Finding, RiskScore, Severity
from pluto_aguard.scanners.ai_config_scanner import scan_ai_configs
from pluto_aguard.scanners.mcp_scanner import scan_directory
from pluto_aguard.scanners.permission_scanner import (
    calculate_permission_risk_score,
    load_agent_config,
    scan_agent_permissions,
)
from pluto_aguard.scanners.runner import AGENT_CONFIG_FILES, _calculate_risk_score
from pluto_aguard.suppressions import apply_suppressions

console = Console()


def run_evidence(
    path: str,
    config_path: str | None = None,
    policy_path: str | None = None,
    output_path: str = "launch-readiness.md",
) -> None:
    """Generate a launch readiness packet for an agent project."""
    project_path = Path(path).resolve()
    console.print("\n📋 [bold]Generating launch readiness packet[/bold]\n")
    console.print(f"  [dim]Scanning project:[/dim] {project_path}")
    findings, permission_scores, scanned_configs = _collect_project_state(project_path)

    config_data: dict[str, Any] | None = None
    config_display = "Not provided"
    if config_path:
        config_file = Path(config_path).resolve()
        config_display = str(config_file)
        console.print(f"  [dim]Loading config:[/dim] {config_file}")
        config_data = load_agent_config(config_file)
        if config_file not in scanned_configs:
            findings.extend(scan_agent_permissions(config_file, config_data))
            permission_scores.append(calculate_permission_risk_score(config_data))

    policy_data: dict[str, Any] | None = None
    policy_display = "Not provided"
    if policy_path:
        policy_file = Path(policy_path).resolve()
        policy_display = str(policy_file)
        console.print(f"  [dim]Loading policy:[/dim] {policy_file}")
        policy_data = _load_yaml(policy_file)

    suppression = apply_suppressions(findings, project_path)
    findings = suppression.kept
    if suppression.suppressed_count:
        console.print(f"  [dim]{suppression.suppressed_count} finding(s) suppressed[/dim]")

    risk_score = _calculate_risk_score(findings, permission_scores)
    markdown = _render_markdown(
        project_path=project_path,
        config_display=config_display,
        policy_display=policy_display,
        findings=findings,
        risk_score=risk_score,
        config_data=config_data,
        policy_data=policy_data,
    )

    output_file = Path(output_path)
    output_file.write_text(markdown, encoding="utf-8")
    console.print(f"\n  ✅ Launch readiness packet saved to [bold]{output_file}[/bold]\n")


def _collect_project_state(project_path: Path) -> tuple[list[Finding], list[float], set[Path]]:
    findings = scan_directory(project_path)
    findings.extend(scan_ai_configs(project_path))
    permission_scores: list[float] = []
    scanned_configs: set[Path] = set()

    for config_name in AGENT_CONFIG_FILES:
        for config_file in project_path.rglob(config_name):
            try:
                config = load_agent_config(config_file)
            except (OSError, ValueError):
                continue

            scanned_configs.add(config_file.resolve())
            findings.extend(scan_agent_permissions(config_file, config))
            permission_scores.append(calculate_permission_risk_score(config))

    return findings, permission_scores, scanned_configs


def _load_yaml(path: Path) -> dict[str, Any]:
    content = path.read_text(encoding="utf-8")
    data = yaml.safe_load(content) or {}
    return data if isinstance(data, dict) else {}


def _render_markdown(
    project_path: Path,
    config_display: str,
    policy_display: str,
    findings: list[Finding],
    risk_score: RiskScore,
    config_data: dict[str, Any] | None,
    policy_data: dict[str, Any] | None,
) -> str:
    counts = risk_score.finding_count
    critical = int(counts.get(Severity.CRITICAL, 0))
    high = int(counts.get(Severity.HIGH, 0))
    medium = int(counts.get(Severity.MEDIUM, 0))
    low = int(counts.get(Severity.LOW, 0))

    lines = [
        "# Agent Launch Readiness Packet",
        f"Generated by Pluto AgentGuard v{__version__} | {datetime.now().strftime('%Y-%m-%d')}",
        "",
        "## Agent Overview",
        f"- **Project path:** {project_path}",
        f"- **Config file:** {config_display}",
        f"- **Policy file:** {policy_display}",
        "",
        "## Risk Summary",
        f"- **Overall Risk Score:** {risk_score.overall:.1f}/100 ({_risk_level(risk_score.overall)})",
        f"- **Findings:** {critical} critical, {high} high, {medium} medium, {low} low",
        "",
        "## Security Findings",
    ]

    if findings:
        for finding in _sorted_findings(findings):
            lines.extend([
                f"### {finding.severity.value.upper()}: {finding.title}",
                f"- **OWASP ID:** {finding.owasp_id or 'N/A'}",
                f"- **Description:** {finding.description}",
                f"- **Remediation:** {finding.remediation or 'Review and remediate before launch.'}",
                "",
            ])
    else:
        lines.extend(["- No findings detected.", ""])

    lines.extend(["## Tool Permissions"])
    if config_data is None:
        lines.extend(["- Config not provided.", ""])
    else:
        lines.extend(_render_tool_permissions(config_data))
        lines.append("")

    lines.extend(["## Policy Coverage"])
    if policy_data is None:
        lines.extend(["- Policy not provided.", ""])
    else:
        lines.extend(_render_policy_coverage(policy_data))
        lines.append("")

    lines.extend(["## Required Mitigations"])
    mitigations = [
        finding for finding in _sorted_findings(findings) if finding.severity in {Severity.CRITICAL, Severity.HIGH}
    ]
    if mitigations:
        for finding in mitigations:
            remediation = finding.remediation or "Review and remediate before launch."
            lines.append(f"- [ ] {finding.title} — {remediation}")
    else:
        lines.append("- [x] No HIGH or CRITICAL findings detected")
    lines.extend([
        "",
        "## Launch Approval Checklist",
        "- [ ] All CRITICAL findings resolved",
        "- [ ] All HIGH findings resolved or accepted with justification",
        "- [ ] Human-in-the-loop gates configured for dangerous tools",
        "- [ ] Secrets removed from configuration files",
        "- [ ] Rate limits and timeouts configured",
        "- [ ] Agent policy file created and reviewed",
        "- [ ] Behavioral monitoring enabled",
        "- [ ] Launch approved by: _______________",
        "- [ ] Date: _______________",
        "",
    ])
    return "\n".join(lines)


def _render_tool_permissions(config_data: dict[str, Any]) -> list[str]:
    lines: list[str] = []
    tools = config_data.get("tools", config_data.get("allowed_tools", []))
    permissions = config_data.get("permissions", {})

    if not isinstance(tools, list) or not tools:
        return ["- No tools declared."]

    for tool in tools:
        if isinstance(tool, dict):
            tool_name = str(tool.get("name", "unknown"))
        else:
            tool_name = str(tool)
        lines.append(f"- `{tool_name}`: {_permission_level(tool_name, permissions)}")

    return lines


def _permission_level(tool_name: str, permissions: Any) -> str:
    if not isinstance(permissions, dict):
        return "undeclared"

    tool_permissions = permissions.get(tool_name, permissions.get(tool_name.lower(), "undeclared"))
    if isinstance(tool_permissions, dict):
        if "scope" in tool_permissions:
            return str(tool_permissions["scope"])
        if not tool_permissions:
            return "declared"
        return ", ".join(f"{key}={value}" for key, value in tool_permissions.items())
    if isinstance(tool_permissions, str):
        return tool_permissions
    return "undeclared"


def _render_policy_coverage(policy_data: dict[str, Any]) -> list[str]:
    allowed_tools = policy_data.get("allowed_tools", [])
    denied_tools = policy_data.get("denied_tools", [])
    hitl_requirements = policy_data.get("require_human_approval", policy_data.get("human_in_the_loop", []))
    data_access_rules = policy_data.get("data_access_rules", policy_data.get("data_access", {}))

    return [
        f"- **Allowed tools:** {_format_list(allowed_tools)}",
        f"- **Denied tools:** {_format_list(denied_tools)}",
        f"- **HITL requirements:** {_format_list(hitl_requirements)}",
        f"- **Data access rules:** {_format_data_access(data_access_rules)}",
    ]


def _format_list(values: Any) -> str:
    if isinstance(values, list) and values:
        return ", ".join(str(value) for value in values)
    return "None declared"


def _format_data_access(data_access_rules: Any) -> str:
    if isinstance(data_access_rules, dict) and data_access_rules:
        return ", ".join(f"{resource} ({access})" for resource, access in data_access_rules.items())
    return "None declared"


def _sorted_findings(findings: list[Finding]) -> list[Finding]:
    severity_order = {
        Severity.CRITICAL: 0,
        Severity.HIGH: 1,
        Severity.MEDIUM: 2,
        Severity.LOW: 3,
        Severity.INFO: 4,
    }
    return sorted(findings, key=lambda finding: (severity_order[finding.severity], finding.title))


def _risk_level(score: float) -> str:
    if score >= 75:
        return "Critical"
    if score >= 50:
        return "High"
    if score >= 25:
        return "Medium"
    return "Low"
